

# ===============================
# = Hibernate datasource
# ===============================
spring:
  port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/kjKhoza?useSSL=false
    username: developer
    password: password

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO